refactor the model generation and unified it with enums and constants.
contiamo/openapi-generator-go pull request #7
Opened 2020-12-10 12:58 UTC by trusch

refactor the model generation and unified it with enums and constants.

## Ticket

## How Has This Been Verified?
extended the tests and the existing ones are still passing

## Checklist:

- [x] The change works as expected.
- [x] New code can be debugged via logs.
- [x] I have added tests to cover my changes.
- [x] I have locally run the tests and all new and existing tests passed.
- [ ] Requires updates to the documentation.
- [ ] I have made the required changes to the documents.

2020-12-11 08:22 UTC, LucasRoesler commented
@trusch there is a lot of overlap with #6 can we merge that first? It will help reduce the scope of this PR and make it easier to review.

2020-12-11 08:26 UTC, trusch commented
sure @LucasRoesler

2020-12-11 15:38 UTC, LucasRoesler commented on pkg/generators/models/testdata/cases/enum/api.yaml
> +    Foo:
Let's make this easier to read 
```suggestion
    Name:
```

2020-12-11 15:42 UTC, LucasRoesler commented on pkg/generators/models/testdata/cases/const/api.yaml
> +    Foo:
Why new tests cases, there are already cases for 

`contants` https://github.com/contiamo/openapi-generator-go/tree/master/pkg/generators/models/testdata/cases/constants

and `enums` https://github.com/contiamo/openapi-generator-go/tree/master/pkg/generators/models/testdata/cases/enums

2020-12-11 15:51 UTC, LucasRoesler requested changes
It looks good, but let's remove the unused testdata files

2020-12-15 09:43 UTC, LucasRoesler approved these changes

2020-12-15 10:42 UTC, merged